[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
stellalpha_vault = "64XogE2RvY7g4fDp8XxWZxFTycANjDK37n88GZizm5nx"

[programs.localnet]
stellalpha_vault = "AtJ1j39GKPLutkFBLe3xkBsSuTG2GfwmN3833mATEwaj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
